apiVersion: v1
kind: Service
metadata:
  name: prometheus-kafka-adapter
  namespace: integraciones
  labels:
    app: prometheus-kafka-adapter
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: prometheus-kafka-adapter
