apiVersion: v1
kind: Service
metadata:
  name: snmp-exporter
  namespace: integraciones
  labels:
    app: snmp-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9116
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: snmp-exporter
